# Generated by Django 4.2 on 2023-05-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_answer_question_points_alter_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='description',
            field=models.TextField(default='Описание', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
