# Generated by Django 4.2 on 2023-05-13 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_university_universityfact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniversityFact',
            new_name='UniversityLeftFact',
        ),
        migrations.AddField(
            model_name='university',
            name='fact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Факт'),
        ),
        migrations.AlterField(
            model_name='university',
            name='href',
            field=models.CharField(max_length=255, verbose_name='Ссылка на университет'),
        ),
        migrations.CreateModel(
            name='UniversityRightFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Факт')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.university')),
            ],
        ),
    ]
