# Generated by Django 4.2 on 2023-05-13 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_universityfact_universityleftfact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='abb',
            field=models.CharField(blank=True, max_length=255, verbose_name='Аббревиатура'),
        ),
    ]
