# Generated by Django 4.2 on 2023-05-17 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_university_abb'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='university',
            name='amount_of_students',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Количество студентов'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название специальности')),
                ('code', models.CharField(max_length=255, verbose_name='Код')),
                ('minimum_ball', models.PositiveSmallIntegerField(verbose_name='Пороговый балл')),
                ('minimum_grant_ball', models.PositiveSmallIntegerField(verbose_name='Минимальный балл')),
                ('maximum_ball', models.PositiveSmallIntegerField(verbose_name='Максимальный балл')),
                ('avg_ball', models.PositiveSmallIntegerField(verbose_name='Средний балл')),
                ('amount_of_grants', models.PositiveSmallIntegerField(verbose_name='Количество грантов')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.university')),
            ],
        ),
        migrations.AddField(
            model_name='university',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.universitycategory'),
        ),
    ]
